version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=true
